//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giver
    {
        public string Journal { get; set; }
        public string Navn { get; set; }
        public string Att { get; set; }
        public string Adresse { get; set; }
        public string Postnr { get; set; }
        public string By { get; set; }
        public Nullable<System.DateTime> AflevDato { get; set; }
        public string Registrator { get; set; }
        public string Note { get; set; }
        public Nullable<int> JournalID { get; set; }
        public int GiverID { get; set; }
    
        public virtual Journaler Journaler { get; set; }
    }
}
