//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journaler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journaler()
        {
            this.Arkivalie = new HashSet<Arkivalie>();
            this.Bibliotek = new HashSet<Bibliotek>();
            this.Giver = new HashSet<Giver>();
            this.Kort = new HashSet<Kort>();
            this.Sekvenser = new HashSet<Sekvenser>();
        }
    
        public string JournalNb { get; set; }
        public Nullable<System.DateTime> Afleveret { get; set; }
        public string MedieArt { get; set; }
        public Nullable<double> Antal { get; set; }
        public Nullable<double> Regs { get; set; }
        public string Note { get; set; }
        public int JournalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arkivalie> Arkivalie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bibliotek> Bibliotek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giver> Giver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kort> Kort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sekvenser> Sekvenser { get; set; }
    }
}
